# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-16 16:09
from __future__ import unicode_literals

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180109_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=embed_video.fields.EmbedVideoField(null=True),
        ),
    ]
